name: Build and Deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    name: Build and Deploy Affected Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect Changed Images
        id: detect-changes
        run: |
          chmod +x ./build_resolver.sh
          ./build_resolver.sh
        env:
          GITHUB_ENV: $GITHUB_ENV

      - name: Build and Deploy
        run: |
          echo "Building and deploying ${{ steps.detect-changes.outputs.changed_images }}" 
