name: detect-changed-images.yaml

on:
  workflow_call:
    outputs:
      images:
        description: "Gives back a list of images that need rebuilt based on files changed"
        value: ${{ jobs.changed-images.outputs.images }}
    inputs:
      TAG_VERSION:
        description: "Specify the tag to build (must exist in the format v<major>.<minor>.<patch>)"
        required: true
        type: string
      USE_LAST_TAG:
        description: "Tell the build resolver script which tag to use for comparison"
        type: boolean
        required: false

jobs:
  changed-images:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.export-images.outputs.images }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.TAG_VERSION }}
          fetch-depth: 0

      - name: Run build_resolver.sh
        id: resolve-changes
        run: |
          chmod +x build_resolver.sh
          if [[ "${{ inputs.USE_LAST_TAG }}" == "true" ]]; then
            echo "Calling build resolver with use_last"
            ./build_resolver.sh use_last
          else
            ./build_resolver.sh
          fi 

      - name: Export Changed Images
        id: export-images
        run: |
          if [[ -n "$changed_images" ]]; then
            # Convert the matrix eligable list
            echo "images=$(echo '["'${changed_images//,/\",\"}'"]')" >> $GITHUB_OUTPUT
          else
            echo "images=[]" >> $GITHUB_OUTPUT
          fi