name: handle-release-pr-merged

on:
  pull_request:
    types:
      - closed

jobs:
  handle-release-pr:
    name: handle-release-pr
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.base.ref == 'main' &&
      startsWith(github.event.pull_request.head.ref, 'release/') &&
      ${{ github.event.pull_request.merged }}
    outputs:
      status: ${{ steps.set-outputs.outputs.status }}
      tag: ${{ steps.set-outputs.outputs.tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Action on PR Closure
        run: |
          echo "PR merged. Proceeding to tag release."
          echo "Head ref is: ${{ github.event.pull_request.head.ref }}"
          echo "Event commit msg: ${{ github.event.head_commit.message }}"
          # Extract version from the branch name
          RELEASE_BRANCH="${GITHUB_HEAD_REF:-${{ github.event.pull_request.head.ref }}}"
          if [[ "$RELEASE_BRANCH" == release/* ]]; then
            VERSION="${RELEASE_BRANCH#release/}"
            echo "Version extracted: $VERSION"
            echo "release_version=$VERSION" >> $GITHUB_ENV
          else
            echo "Branch name does not follow the 'release/' pattern. Exiting."
            exit 1
          fi

      - name: Create Tag and Release (Only for Merged PR)
        run: |
          echo "Release version: ${{ env.release_version }}"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          RELEASE_BRANCH="${GITHUB_HEAD_REF:-${{ github.event.pull_request.head.ref }}}"
          git tag -a "${{ env.release_version }}" -m "Release ${{ env.release_version }}"
          #git push origin "${{ env.release_version }}"
          git push --tags
          
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d @- << EOF
          {
            "tag_name": "${{ env.release_version }}",
            "name": "Release ${{ env.release_version }}",
            "body": "Automated release for version ${{ env.release_version }}",
            "draft": false,
            "prerelease": false
          }
          EOF

      - name: Label PR as Released
        if: ${{ github.event.pull_request.merged }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          
          LABELS=$(gh issue view "$PR_NUMBER" --repo "$REPO" --json labels -q ".labels[].name" | paste -sd "," -)
          
          if echo "$LABELS" | grep -q "release: pending"; then
          gh issue edit "$PR_NUMBER" --repo "$REPO" --remove-label "release: pending"
          fi
          
          gh issue edit "$PR_NUMBER" --repo "$REPO" --add-label "release: tagged"

      - name: Save Tag version
        env:
          TAG: ${{ env.release_version }}"
        run: |
          mkdir -p ./tag
          echo $TAG > ./tag/tag_version

      - uses: actions/upload-artifact@v4
        with:
          name: tag_version
          path: tag/
