name: periodic-cve-scan-published-images.yaml

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight

jobs:
  matrix-scans:
    name: scan-images-with-grype-and-trivy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - telicent/telicent-python3.12:latest
          - telicent/telicent-python3.11:latest
          - telicent/telicent-nginx1.27:latest
          - telicent/telicent-java21:latest
          - telicent/telicent-nodejs20:latest
        scanner:
          - grype
          - trivy
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Grype Image Scan
        if: matrix.scanner == 'grype'
        uses: telicent-oss/shared-workflows/.github/workflows/grype-image-scan.yml@main
        with:
          image: ${{ matrix.image }}

      - name: Run Trivy Image Scan
        if: matrix.scanner == 'trivy'
        uses: telicent-oss/shared-workflows/.github/workflows/trivy-image-scan.yml@main
        with:
          image: ${{ matrix.image }}
