name: periodic-cve-scan-published-images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight

jobs:
  grype-scans:
    name: scan-images-with-grype
    uses: telicent-oss/shared-workflows/.github/workflows/grype-image-scan.yml@main
    strategy:
      matrix:
        image-artifact:
          - { image: "telicent/telicent-python3.12:latest", artifact: "telicent-python3.12" }
          - { image: "telicent/telicent-python3.11:latest", artifact: "telicent-python3.11" }
          - { image: "telicent/telicent-nginx1.27:latest", artifact: "telicent-nginx1.27" }
          - { image: "telicent/telicent-java21:latest", artifact: "telicent-java21" }
          - { image: "telicent/telicent-nodejs20:latest", artifact: "telicent-nodejs20" }
      fail-fast: false
    with:
      IMAGE_REF: ${{ matrix.image-artifact.image }}
      SCAN_NAME: ${{ matrix.image-artifact.artifact }}
    secrets: inherit

  trivy-scans:
    name: scan-images-with-trivy
    uses: telicent-oss/shared-workflows/.github/workflows/trivy-image-scan.yml@main
    strategy:
      matrix:
        image-artifact:
          - { image: "telicent/telicent-python3.12:latest", artifact: "telicent-python3.12" }
          - { image: "telicent/telicent-python3.11:latest", artifact: "telicent-python3.11" }
          - { image: "telicent/telicent-nginx1.27:latest", artifact: "telicent-nginx1.27" }
          - { image: "telicent/telicent-java21:latest", artifact: "telicent-java21" }
          - { image: "telicent/telicent-nodejs20:latest", artifact: "telicent-nodejs20" }
      fail-fast: false
    with:
      IMAGE_REF: ${{ matrix.image-artifact.image }}
      SCAN_NAME: ${{ matrix.image-artifact.artifact }}
    secrets: inherit
