name: periodic-cve-scan-published-images

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight

jobs:
  grype-scans:
    name: scan-images-with-grype
    uses: telicent-oss/shared-workflows/.github/workflows/grype-image-scan.yml@main
    strategy:
      matrix:
        image:
          - telicent/telicent-python3.12:latest
          - telicent/telicent-python3.11:latest
          - telicent/telicent-nginx1.27:latest
          - telicent/telicent-java21:latest
          - telicent/telicent-nodejs20:latest
      fail-fast: false
    with:
      image: ${{ matrix.image }}

  trivy-scans:
    name: scan-images-with-trivy
    uses: telicent-oss/shared-workflows/.github/workflows/trivy-image-scan.yml@main
    strategy:
      matrix:
        image:
          - telicent/telicent-python3.12:latest
          - telicent/telicent-python3.11:latest
          - telicent/telicent-nginx1.27:latest
          - telicent/telicent-java21:latest
          - telicent/telicent-nodejs20:latest
      fail-fast: false
    with:
      image: ${{ matrix.image }}
