name: prepare-custom-release.yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changed-images:
    name: Detect Changes
    #&& !contains(github.event.head_commit.message, 'release')
    if: ${{ github.event.head_commit.author.name != 'github-actions[bot]' || contains(github.event.head_commit.message, 'chore(bot)') }}
    uses: ./.github/workflows/detect-changed-images.yaml
    with:
     TAG_VERSION: ${{ github.ref }}
     USE_LAST_TAG: true

  create-release-pr:
    needs: [changed-images]
    # The job will only run if the 'images' output from the previous job is not empty.
    if: ${{ needs.changed-images.outputs.images != '["[]"]' }}
    name: create-or-update-release-pr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Next Release Version
        id: determine-version
        run: |
          ./tag_version.sh

      - name: Issue Warning if Merging with No Releasable changes
        if: ${{ steps.determine-version.outputs.new_version == '' }}
        run: |
          echo "::warning title=No Releasable Changes Detected::No releasable changes were detected. Remember you MUST use conventional commit style messages for releases to be automatically generated!"
          exit 1

      - name: Update Versions in Image Descriptors
        id: update-versions
        run: |
          echo "Updating image descriptors for version ${{ steps.determine-version.outputs.new_version }}."
          echo "Images to update: ${{ needs.changed-images.outputs.images }}"
          ./update_version.sh ${{ needs.changed-images.outputs.images }}

      - name: Append Changelog
        id: generate-changelog
        run: |
          ./generate_changelog.sh ${{ steps.determine-version.outputs.new_version }}

      - name: Commit Changes and Create Release Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: prepare release ${{ steps.determine-version.outputs.new_version }}" || echo "No changes to commit."

      - name: Open or Update Release PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: prepare release ${{ steps.determine-version.outputs.new_version }}"
          base: ${{ github.event.repository.default_branch }}
          branch: release/${{ steps.determine-version.outputs.new_version }}
          title: "chore: prepare release ${{ steps.determine-version.outputs.new_version }}"
          body: |
            ## Changes 
            ${{ steps.generate-changelog.outputs.new_changelog }}
          labels: "release: pending"