name: Release Please

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: .github/release-please-config.json
          target-branch: main
          path: .
          manifest-file: .github/release-please-manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}