name: Create or Update Release Branch

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  create-tag:
    name: Create Release Tag
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref_name, 'release/') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Extract Tag from Branch Name
        id: determine-version
        run: |
          # Extract the branch name
          RELEASE_BRANCH="${{ github.event.head_commit.ref }}"
          if [[ $RELEASE_BRANCH != refs/heads/release/* ]]; then
            echo "Not a release branch. Exiting."
            exit 1
          fi
          # Extract version from the branch name
          VERSION="${RELEASE_BRANCH#refs/heads/release/}"
          echo "New tag: $VERSION"
          echo "new_tag=$VERSION" >> $GITHUB_ENV
      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ env.new_tag }}" -m "Release ${{ env.new_tag }}"
          git push origin "${{ env.new_tag }}"

  changed-images:
    if: "github.event_name == 'push' && ${{ !contains(github.ref_name, 'release/') }}"
    name: Detect Changes
    uses: ./.github/workflows/detect-changed-images.yaml

  create-release-pr:
    name: Create or Update Release PR
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' && ${{ !contains(github.ref_name, 'release/') }}"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Next Release Version
        id: determine-version
        run: |
          # Extract the last release tag
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"
          # Extract version numbers
          VERSION_PARTS=($(echo "${LAST_TAG}" | sed 's/v//' | tr '.' ' '))
          MAJOR=${VERSION_PARTS[0]:-0}
          MINOR=${VERSION_PARTS[1]:-0}
          PATCH=${VERSION_PARTS[2]:-0}
          # Determine bump type based on commit messages
          if git log "$LAST_TAG"..HEAD --oneline | grep -q "BREAKING CHANGE:"; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif git log "$LAST_TAG"..HEAD --oneline | grep -q "feat:"; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif git log "$LAST_TAG"..HEAD --oneline | grep -q -E "fix:|chore:"; then
            PATCH=$((PATCH + 1))
          fi
          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Prepare or Update Release Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Check if release branch exists
          if git ls-remote --exit-code --heads origin release/${{ env.new_version }}; then
            echo "Branch release/${{ env.new_version }} already exists. Checking out and rebasing."
            git fetch origin release/${{ env.new_version }}:release/${{ env.new_version }}
            git checkout release/${{ env.new_version }}
            git rebase dev
          else
            echo "Branch release/${{ env.new_version }} does not exist. Creating a new branch."
            git checkout -b release/${{ env.new_version }} dev
          fi

      - name: Update Versions in Image Descriptors
        run: |
          echo "Updating image descriptors for version ${{ env.new_version }}."
          ./update_version.sh ${{ needs.changed-images.outputs.images }} || { echo "Version update failed. Exiting."; exit 1; }

      - name: Append Changelog
        id: generate-changelog
        run: |
          ./generate_changelog.sh >> CHANGELOG.md
          echo "Generated changelog:"
          cat CHANGELOG.md

      - name: Commit Changes and Push Release Branch
        run: |
          git add .
          git commit -m "chore: prepare release ${{ env.new_version }}" || echo "No changes to commit."
          git push --force origin release/${{ env.new_version }}

      - name: Open or Update Release PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: prepare release ${{ env.new_version }}"
          base: dev
          branch: release/${{ env.new_version }}
          title: "chore: prepare release ${{ env.new_version }}"
          body: |
            ## Changes
            ${{ steps.generate-changelog.outputs.changelog }}
          labels: "release: pending"