name: Create or Update Release Branch

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  create-release-pr:
    name: Create or Update Release PR
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'Merge branch \'release/') # Skip on release branch merges
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Next Release Version
        id: determine-version
        run: |
          # Extract the last release tag
          LAST_TAG=$(git describe --tags --abbrev=0 HEAD^ || echo "v0.0.0")
          echo "Last tag: $LAST_TAG"

          # Extract version numbers
          VERSION_PARTS=($(echo "${LAST_TAG}" | sed 's/v//' | tr '.' ' '))
          MAJOR=${VERSION_PARTS[0]:-0}
          MINOR=${VERSION_PARTS[1]:-0}
          PATCH=${VERSION_PARTS[2]:-0}

          # Determine bump type based on commit messages
          if git log "$LAST_TAG"..HEAD --oneline | grep -q "BREAKING CHANGE:"; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif git log "$LAST_TAG"..HEAD --oneline | grep -q "feat:"; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif git log "$LAST_TAG"..HEAD --oneline | grep -q -E "fix:|chore:"; then
            PATCH=$((PATCH + 1))
          fi

          NEW_VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "New version: $NEW_VERSION"

          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Prepare or Update Release Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Check if release branch exists
          if git ls-remote --exit-code --heads origin release/${{ env.new_version }}; then
            echo "Branch release/${{ env.new_version }} already exists. Checking out and rebasing."
            git fetch origin release/${{ env.new_version }}:release/${{ env.new_version }}
            git checkout release/${{ env.new_version }}
            git rebase dev
          else
            echo "Branch release/${{ env.new_version }} does not exist. Creating a new branch."
            git checkout -b release/${{ env.new_version }} dev
          fi

          echo "Updating version and changelog."
          ./update_version.sh || { echo "Version update failed. Exiting."; exit 1; }

      - name: Generate Changelog
        id: generate-changelog
        run: |
          ./generate_changelog.sh > CHANGELOG.md
          cat CHANGELOG.md

          # Save the changelog to output for the PR body
          echo "changelog<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Commit Changes and Push Release Branch
        run: |
          git add .
          git commit -m "chore: prepare release ${{ env.new_version }}" || echo "No changes to commit."
          git push --force origin release/${{ env.new_version }}

      - name: Open or Update Release PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: prepare release ${{ env.new_version }}"
          base: dev
          branch: release/${{ env.new_version }}
          title: "chore: prepare release ${{ env.new_version }}"
          body: |
            ${{ env.changelog }}
          labels: "release: pending"

  create-tag:
    name: Tag Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Update PR Label to `release: tagged`"
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label "release: tagged"

      - name: Extract Tag from Branch Name
        id: determine-version
        run: |
          # Extract version from release branch
          RELEASE_BRANCH="${{ github.event.pull_request.head.ref }}"
          VERSION=${RELEASE_BRANCH#release/}
          echo "New tag: $VERSION"
          echo "new_tag=$VERSION" >> $GITHUB_ENV

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "${{ env.new_tag }}" -m "Release ${{ env.new_tag }}"
          git push origin "${{ env.new_tag }}"
