name: Build Images

on:
  push:
    branches:
      - dev

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build_resolver.sh
        run: |
          chmod +x build_resolver.sh
          ./build_resolver.sh

  build-images:
    needs: determine-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ env.changed_images && fromJson('["' + env.changed_images.replace(',', '","') + '"]') || [] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Deploy Image
        run: |
          echo "Building image for: ${{ matrix.image }}" 
