name: Build Images

on:
  push:
    branches:
      - main

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.export-images.outputs.images }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build_resolver.sh
        id: resolve-changes
        run: |
          chmod +x build_resolver.sh
          ./build_resolver.sh

      - name: Export Changed Images
        id: export-images
        run: |
          if [[ -n "$changed_images" ]]; then
            # Convert the comma-separated list into JSON
            echo "images=$(echo '[\"'${changed_images//,/\",\"}'\"]')" >> $GITHUB_ENV
          else
            echo "images=[]" >> $GITHUB_ENV
          fi
        env:
          changed_images: $changed_images
        outputs:
          images: ${{ env.images }}

  build-images:
    needs: determine-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.determine-changes.outputs.images) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Deploy Image
        run: |
          echo "Building image for: ${{ matrix.image }}"
