name: descriptor-updater

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *' # Daily at 9am GMT

permissions:
  contents: write
  pull-requests: write

jobs:
  update-descriptors:
    name: Run Descriptor Updater
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Descriptor Updater
        run: |
          python descriptor-updater.py

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot-dependencies]"
          git config user.email "41898282+github-actions[bot-dependencies]@users.noreply.github.com"
          git add .
          git commit -m "chore: update descriptors" || echo "No changes to commit."

      - name: Open or Update PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update descriptors ubi9 version"
          base: main
          branch: chore/update-descriptors
          title: "Chore(bot): update ubi9 version in descriptors"
          body: |
            This PR updates the descriptors using the latest released versions of ubi9 minimal.
          labels: "chore"
